### ISSUE TITLE
Application dies on wake from sleep

### ISSUE THREAD

**Issue by superevr** [artginzburg/MiddleClick-Ventura#19]
macOS 10.15.2 MacBook Pro 16-inch 2019

MiddleClick is not running after my mac wakes up from sleep.

**Comment by drbradfo** [comment]
I'm also experiencing MiddleClick crashing on sleep.

macOS 10.15.2. MacBook Pro 15-inch 2018.

**Comment by hamzamerzic** [comment]
+1 
macOS 10.15.2. MacBook Pro 13-inch 2017.

**Comment by Jont828** [comment]
+1,  running 10.15.1 on the 16 inch MBP

**Comment by mofolo** [comment]
Same problem.

**Comment by yedpodtrzitko** [comment]
Same problem with the latest version. 

I tried to run it from shell, to see if it will report any error, and it actually helped - it displayed the dialog about Accessibility Settings (which didn't appear otherwise when starting it via Spotlight). So I disabled & re-enabled it there, which solved the issue.

**Comment by kgorol** [comment]
Application also dies for me on 10.14.6

**Comment by thermistor** [comment]
Disabling and reenabling did not solve it for me. It's still gone on wake from sleep.

**Comment by jackblk** [comment]
I use this one to auto restart app after sleep:

`defaults write com.rouge41.middleClick autoRestartOnWake -int 2`

**Comment by svuhoang** [comment]
Running into this issue currently with MBP M1 Pro.

Auto restart app after sleep works, but doesn't work immediately after wake since it needs to restart. Is there a better solution?

**Comment by OnlineBlazeBoy** [comment]
I have the same issue with the MacBook Pro 14-inch with the M1 Pro.

I tried the auto-restart on wake but the app just crashes/quits (showing the loading colour wheel when I hover over the menu bar icon) after a few seconds.

Also tried disabling and re-enabling accessibility permissions and removing and re-adding to login items.

Nothing seems to be working.

**Comment by ElectricS01** [comment]
Also dies for me when it sleeps

**Comment by shanep2300** [comment]
> I use this one to auto restart app after sleep:
> 
> `defaults write com.rouge41.middleClick autoRestartOnWake -int 2`

This didn't work for me either. The only thing that works is closing the app and reopening it.

**Comment by artginzburg** [comment]
You should try out the new [pre-release](https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.6), it fixed all the issues of this kind for me (I'm on macOS 12.6).

**Comment by StevenHa0** [comment]
Thanks, that worked for me! I'm also on macOS 12.6 - M1 MacBook Air.

**Comment by artginzburg** [comment]
> I use this one to auto restart app after sleep:
> 
> `defaults write com.rouge41.middleClick autoRestartOnWake -int 2`

@jackblk where did you find this setting? I now realised that it was added to Readme just because 2 people reported using it. Then I've seen 2+ people saying that it doesn't help. Also tried it myself, and it did not change anything apparently. This setting does not exist in the code of this repository, or LoPablo's fork, or the base fork.

It should probably be removed from Readme not to confuse anyone.

**Comment by jackblk** [comment]
@artginzburg I found it here from another developer with a similar app: https://www.reddit.com/r/MacOS/comments/mijjf0/middleclick_application_keeps_closing/gy4z44m/

I'm not sure if it works for everyone, but it works for some including me. Maybe adding a note saying it might or might not work?

**Comment by artginzburg** [comment]
Ah, now I remember. Looks like me and possibly some other people asked for a fix to this issue in email to Ryan (the dev of Middle) ~1.5 years ago, and this is the solution he came up with. And it worked for me in Middle. This setting was never implemented in MiddleClick though. I should probably add it if we don't come up with a final stable fix.
