### ISSUE TITLE
MiddleClick doesn't work because it starts before Magic Mouse

### ISSUE THREAD

**Issue by jordiramu** [artginzburg/MiddleClick-Ventura#28]
Hello,

First I'd like to thank you for the great app!

I use MiddleClick on a M1 iMac (24", 2021) with MacOS updated to Monterey.

Whenever I restart and then login, MiddleClick seems to start too fast; it is set as a startup item.
It looks like MiddleClick starts just before the default (included in the package) Magic Mouse is initialized and as a result it doesn't work.
So.. the middle click functionality implemented by MiddleClick.app is not present unless I quit MiddleClick application and start it again, manually; but this makes it unusable as a start item.

As a workaround I used Automator to create a new app which runs a very simple Bash command (actually two):
sleep 5 && open -a MiddleClick
and had this Automator generated app set as a startup item instead.

Is there any way to make MiddleClick activate/load/set its functionality after the mouse is initialized?

Thank you

**Comment by jordiramu** [comment]
Sorry, I forgot the following:
george@iMac-de-George ~ % brew info middleclick
middleclick: 2.5
https://github.com/artginzburg/MiddleClick-BigSur
/opt/homebrew/Caskroom/middleclick/2.5 (125B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/middleclick.rb
==> Name
MiddleClick
==> Description
Utility to extend trackpad functionality
==> Artifacts
MiddleClick.app (App)
==> Analytics
install: 476 (30 days), 771 (90 days), 1,760 (365 days)
george@iMac-de-George ~ %

**Comment by stealthpro** [comment]
I have the same problem after wake up.

**Comment by jordiramu** [comment]
After coecting an Apple Trackpad I also needed to restart MiddleClick to make it work with the trackpad.

**Comment by grishka** [comment]
When the trackpad disconnects by itself (because of course it does, it's wireless for some reason and wireless is a synonym for unreliable) and then reconnects, I also have to restart MiddleClick to make it work again, which is annoying.

**Comment by artginzburg** [comment]
You should try out the new [pre-release](https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.6). I haven't tested it with wireless devices, but it's a much more stable build. Please continue here if the issue persists.

**Comment by karlhorky** [comment]
I'm having a similar problem with versions `2.5`, `2.5.0.1` and the prerelease `2.6` (can't test any other versions since I'm on an M1 machine - running macOS 12.6 Monterey):

When disconnecting / reconnecting a Magic Mouse (no sleep/wake cycle), MiddleClick no longer registers middle clicks and the app needs to be restarted.

I was looking into how I could automate restarting the app as a workaround in the meantime, but haven't found a good solution yet.

If I should open a new issue for this issue while reconnecting, happy to do so!

**Comment by karlhorky** [comment]
### Workaround

To quickly restart MiddleClick, use macOS Shortcuts: create a shortcut that closes MiddleClick and opens it again:

<img width="743" alt="Screen Shot 2022-10-09 at 15 27 56" src="https://user-images.githubusercontent.com/1935696/194759844-182acbf4-2b89-4bab-9c1f-42294e5d5d3a.png">

Then right click on the shortcut and select "Add to Dock", for easy access:

<img width="177" alt="Screen Shot 2022-10-09 at 15 32 38" src="https://user-images.githubusercontent.com/1935696/194759848-70dd8eb2-83ad-4b23-b2b9-b02afea8420c.png">

**Comment by karlhorky** [comment]
Ok, I think I found the issue. Seems that the commit [`5aca15e0`](https://github.com/artginzburg/MiddleClick-BigSur/commit/5aca15e0dfdbc7b07e0c72b4df384c682d39f0ea#diff-2185ed73ff59962c5e075a474403402cac1282cc4fc3060f5c94801774282d5dL105-R310) broke this (the removal of the call to `CFRelease(item)` for the M1 build).

I've opened a PR for this, to instead call `IOObjectRelease(item)`: 

![Screenshot 2022-12-05 at 16 27 03](https://user-images.githubusercontent.com/1935696/205675956-beb65ebf-f931-430b-8dbf-36d0f587e856.png)

**Comment by jordiramu** [comment]
Thank you, @karlhorky !
I have tested your patch and it works for me.
Hopefully it will be included with the next release...

**Comment by karlhorky** [comment]
Great, looks like my patch is included in [2.6.1](https://github.com/artginzburg/MiddleClick-Ventura/releases/tag/2.6.1), thanks @artginzburg for the release!
