### ISSUE TITLE
keep closing after couple of hours

### ISSUE THREAD

**Issue by gilaroni** [artginzburg/MiddleClick-Ventura#33]
mac air m1 with Monterey.
I need to reopen the app frequently, I think it closes itself or something.
Any ideas why?

**Comment by kenimou** [comment]
I have similar issue. Need to reopen every time I lock & unlock my laptop.

**Comment by raddi** [comment]
Same here.

**Comment by domenicoCappello** [comment]
I had the same issue after the latest update. Removing the old app permissions from privacy settings fixed things (MBA m1 BigSur 11.6)

**Comment by artginzburg** [comment]
This should be fixed by the [new release](https://github.com/artginzburg/MiddleClick-Ventura/releases/tag/2.6.1). Fixed it for me on Ventura 13.1 with M1 Pro.
