### ISSUE TITLE
two finger click detection

### ISSUE THREAD

**Issue by renehesse** [artginzburg/MiddleClick-Ventura#5]
If you set the whole thing to **Two Fingers** and **Click**, then the action is always triggered if one finger has been on the Magic Mouse for some time and the second finger is added.

For example, if the right finger has been on it for a long time and then you click on it with the left finger, it will be a two finger click.

I think it should only be a two finger click, if no finger has been placed on it before and then two fingers are clicked at the same time.

**Comment by DaFuqtor** [comment]
Apple did it this way for a reason. Idk for what specific reason though. ;)

When I'll have some time, I'll try to do it differently.

**Comment by renehesse** [comment]
Thank you. This would be very helpful, because on a mouse both fingers usually do not float permanently over the device, but one is usually placed and so the other triggers an unwanted double click with a left click.

**Comment by artginzburg** [comment]
Looks like this was fixed in 6da864a.
