### ISSUE TITLE
Not working after sleep mode and need to restart

### ISSUE THREAD

**Issue by Majidahmadi** [artginzburg/MiddleClick-Ventura#53]
Whenever I put the system to sleep, when I come back it doesn't work at all and I have to completely quit and restart it to get it to work.

**Comment by ManuelSch** [comment]
+1

**Comment by Chris-Golle** [comment]
+1

**Comment by artginzburg** [comment]
Have you tried the pre-release? I’m trying to gather feedback on whether it fixes the issue

**Comment by Majidahmadi** [comment]
> Have you tried the pre-release? I’m trying to gather feedback on whether it fixes the issue

Yes, The problem has been solved in version [2.6 — Stability](https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.6)

**Comment by ManuelSch** [comment]
> Have you tried the pre-release? I’m trying to gather feedback on whether it fixes the issue

Waiting for the homebrew formula to provide the newest version, it‘s still at 2.5.0.1

**Comment by Majidahmadi** [comment]
The problem occurs when the system goes to sleep, my scenario is that I closed the system last night without shutting down, and the next day, which is today, after opening the system, it was necessary to close and open it again.

![Screenshot 2022-11-23 at 12 27 15](https://user-images.githubusercontent.com/6078001/203506035-f0b4d0e5-01db-48b4-b6c7-35d11dc5551e.png)

MiddleClick BigSur Version = [2.6 — Stability](https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.6)

**Comment by WhoisGray** [comment]
+1

**Comment by Leong-Qi-Jin** [comment]
Yep I'm still facing this issue as well.

**Comment by artginzburg** [comment]
This should be fixed in the [new release](https://github.com/artginzburg/MiddleClick-Ventura/releases/tag/2.6.1). Reopen the issue with more details if it's not.
