### ISSUE TITLE
Rename to MiddleClick-Sonoma?

### ISSUE THREAD

**Issue by karlhorky** [artginzburg/MiddleClick-Ventura#81]
Hi @artginzburg 👋 hope you're well

Just wanted to reach out because I confirmed today that MiddleClick is working on macOS Sonoma (14.0) (also confirmed by @khesed in https://github.com/artginzburg/MiddleClick-Ventura/issues/77#issuecomment-1703229000 )

Would that be enough to do the following?

- rename the project from the current name `MiddleClick-Ventura` to `MiddleClick-Sonoma`
- make any documentation updates necessary

**Comment by artginzburg** [comment]
Yes, absolutely. I’ve been hoping to rewrite the app in Swift and rename it to WheelClick for clear distinguishing, but for now we can probably stick with renaming the repo to match the macOS version

**Comment by karlhorky** [comment]
Amazing, thanks!
